### ISSUE TITLE
Feature: manual mode

### ISSUE THREAD

**Issue by RageYL** [Carpetsmoker/undofile_warn.vim#1]
Hi,

Thanks for this nice plugin, exactly what i was looking for. 
Could you add a 4th mode: 'manual' ?
When reaching the end of undo history, just echo a message. The user will then have to enter a command like 'LoadUndofile' to load the whole undo history.

Would be greatly apreciated ;)

**Comment by arp242** [comment]
Sounds reasonable.

I'm not sure how to allow people to load the undofile with this. Not a huge fan of adding a new command such as `:AllowUndo`; but there might not be any other way. Need to think about it.

**Comment by RageYL** [comment]
I didn't knew if you were going to reply, here is how i made it: https://gist.github.com/anonymous/f4678bf2caee1daeded825f33f4a5481

**Comment by arp242** [comment]
You can now use `let g:undofile_warn_mode=3` and `:UndofileEnable {no,yes,toggle}` to do what you want.

Thanks for the suggestion!
