### ISSUE TITLE
Can't install this extension by vim-plug

### ISSUE THREAD

**Issue by yan42685** [Carpetsmoker/undofile_warn.vim#2]
![image](https://user-images.githubusercontent.com/41834091/75614270-f64e9a80-5b71-11ea-9770-3c1c74bc7353.png)

**Comment by yan42685** [comment]
the error message shows when I type and save
```
Plug 'undofile_warn.vim'
```
in my vimrc.

**Comment by arp242** [comment]
Use arp242/undofile_warn.vim, or some other GitHub link.

**Comment by yan42685** [comment]
It works. 
Thanks for your help! 😄
